### ISSUE TITLE
[Feature Request]: support WP constants

### ISSUE THREAD

**Issue by luislard** [inpsyde/wp-stubs#5]
### Is your feature request related to a problem?

The stubs does not include WP constants like DAY_IN_SECONDS so we get psalm issues in our PR's

### Describe the desired solution

A file with WP defined constants is included into latest.php

### Describe the alternatives that you have considered

havent thought in an alternative

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gmazzap** [comment]
One of the reasons this repo exists is because alternative packages don't have constants.

So yes, we should have constants.

Here the config that includes constants: https://github.com/inpsyde/wp-stubs/blob/main/generate.php#L41

So not sure why constants are not there...

**Comment by tfrommen** [comment]
I ran into this as well just last week.
In the generated files, there are constants, but very few only.

I don't know if, by default, the parser only looks a `define` and `const` in the global scope, but maybe not in functions? A lot of the default contants are [defined through the `wp_initial_constants` function](https://github.com/WordPress/wordpress-develop/blob/7c254c5510f6e5227e320ea3118f411504f1fe1a/src/wp-includes/default-constants.php#L18).

**Comment by tfrommen** [comment]
Oh, it does indeed seem to be the issue.

https://github.com/php-stubs/generator/blob/bf758105124218225d59e698913ac852ee7d79c7/src/NodeVisitor.php#L136-L138

**Comment by gmazzap** [comment]
@tfrommen we already have a [custom visitor](https://github.com/inpsyde/wp-stubs/blob/main/src/NodeVisitor.php) which is used to generate some class/function stubs from [fixtures](https://github.com/inpsyde/wp-stubs/blob/main/fixtures.php) instead of the WP code.

The purpose is to use advanced Psalm types for argument and return types.

Extending that visitor to also parse functions to extract constants looks like a good idea to me.

**Comment by tfrommen** [comment]
This has been implemented in #7. Closing.
